import { BaseOutline } from '../types';

/**
 * Utility functions for content processing.
 */

/**
 * Generates a full outline context string from all baseOutlines.
 */
export const generateFullOutlineContext = (baseOutlines: BaseOutline[], excludeChaptersForBaseOutlineId?: string): string => {
  if (!baseOutlines || baseOutlines.length === 0) return 'Chưa có dàn ý nào.';
  
  let outline = '';
  baseOutlines.forEach((baseOutline, baseOutlineIndex) => {
    outline += `[Dàn ý cơ sở ${baseOutlineIndex + 1}]: ${baseOutline.title}\n- Tóm tắt: ${cleanContextForAi(baseOutline.summary)}\n`;
    if (baseOutline.chapters && baseOutline.chapters.length > 0 && baseOutline.id !== excludeChaptersForBaseOutlineId) {
      baseOutline.chapters.forEach((chapter, chapterIndex) => {
        outline += `  [Chương ${chapterIndex + 1}]: ${chapter.title}\n  - Tóm tắt: ${cleanContextForAi(chapter.summary)}\n`;
      });
    }
  });
  return outline;
};

/**
 * Generates a full tree context string from all basicOutlineOptions.
 */
export const generateBasicOutlineTreeContext = (options: any[], level: number = 0): string => {
  if (!options || options.length === 0) return '';
  
  let context = '';
  options.forEach((option) => {
    const indent = '  '.repeat(level);
    context += `${indent}[NHÁNH CẤP ${level + 1}]: ${option.title}\n`;
    context += `${indent}- Tóm tắt: ${cleanContextForAi(option.summary)}\n`;
    if (option.keyPlotPoints && option.keyPlotPoints.length > 0) {
      context += `${indent}- Sự kiện chính:\n`;
      option.keyPlotPoints.forEach((point: string) => {
        context += `${indent}  + ${point}\n`;
      });
    }
    if (option.children && option.children.length > 0) {
      context += generateBasicOutlineTreeContext(option.children, level + 1);
    }
  });
  return context;
};

/**
 * Strips beautification tags like <n>, </n>, <content>, </content>, <summary>, </summary>
 * from the text while preserving the content inside them.
 */
export const stripBeautifyTags = (text: string): string => {
  if (!text) return '';
  return text
    .replace(/<n>(.*?)<\/n>/g, '$1')
    .replace(/<\/?content>/g, '')
    .replace(/<\/?summary>/g, '')
    .replace(/<summary>[\s\S]*?<\/summary>/g, '')
    .replace(/^---$/gm, '')
    .replace(/\n---\n/g, '\n\n'); 
};

/**
 * Strips ONLY the tags but keeps the text inside <n>.
 * For <summary> and <content>, it depends on the context.
 * Usually we want to remove the summary block entirely when sending to AI as context
 * because we provide the summary separately.
 */
export const cleanContextForAi = (text: string): string => {
  if (!text) return '';
  return text
    .replace(/<n>(.*?)<\/n>/g, '$1')
    .replace(/<\/?content>/g, '')
    .replace(/<summary>[\s\S]*?<\/summary>/g, '');
};

/**
 * Accurately counts Vietnamese words in a given text.
 * A word is defined as a sequence of letters, numbers, or Vietnamese characters.
 * Hyphenated words (e.g., "e-mail", "ba-ba") are counted as a single word.
 * Punctuation and special characters are ignored.
 */
export const countWords = (text: string): number => {
  if (!text) return 0;
  // Match sequences of word characters, including Vietnamese letters, numbers, and hyphens between characters
  // \p{L} matches any kind of letter from any language
  // \p{N} matches any kind of numeric character
  // The regex matches a word, optionally followed by a hyphen and another word, repeated.
  const words = text.match(/[\p{L}\p{N}_]+(?:-[\p{L}\p{N}_]+)*/gu);
  return words ? words.length : 0;
};

/**
 * Estimates the number of tokens in a given text.
 * This is a heuristic estimation, as true tokenization requires the specific model's tokenizer.
 * Generally, 1 token ~= 4 chars in English, but for Vietnamese it might be different.
 * A common estimation for Vietnamese is ~1.5 to 2.5 tokens per word, or simply length / 3.
 * We'll use a slightly more accurate estimation based on character and word counts.
 */
export const estimateTokens = (text: string): number => {
  if (!text) return 0;
  // A simple but effective heuristic:
  // Count words and add a factor for punctuation/spaces
  // Or simply use character count divided by a factor (e.g., 3.5 for Vietnamese)
  // Let's use a combination: 1 token per word + 1 token per 4 characters of non-word text
  // Actually, Gemini's tokenization for Vietnamese is roughly 1.5 - 2 tokens per word.
  // We can use a simple character-based estimation which is often close enough.
  return Math.ceil(text.length / 3.5);
};

/**
 * Chapters generated by AI sometimes include metadata in the title string using parentheses,
 * such as "Chương 1: Tiêu đề (Kim chỉ nam: ...)" or "Chương 1: Tiêu đề (POV: ...)".
 * This function extracts such metadata, assigns it to the appropriate fields, 
 * and strips it from the final title string.
 */
export const cleanChapterTitleData = (chapter: any): any => {
  if (!chapter || !chapter.title || typeof chapter.title !== 'string') return chapter;

  let { title, storyGuidingPrinciple, pov, ...rest } = chapter;
  
  // Look for (Kim chỉ nam: ...) or (Story Guiding Principle: ...)
  const guidingMatch = title.match(/\(\s*(?:Kim chỉ nam|Story Guiding Principle)\s*:\s*([^)]+)\s*\)/i);
  if (guidingMatch) {
    if (!storyGuidingPrinciple) {
      storyGuidingPrinciple = guidingMatch[1].trim();
    }
    title = title.replace(/\s*\(\s*(?:Kim chỉ nam|Story Guiding Principle)\s*:\s*([^)]+)\s*\)/i, '').trim();
  }

  // Look for (POV: ...)
  const povMatch = title.match(/\(POV\s*:\s*([^)]+)\)/i);
  if (povMatch) {
    if (!pov) {
      pov = povMatch[1].trim();
    }
    title = title.replace(/\s*\(POV\s*:\s*([^)]+)\)/i, '').trim();
  }

  // General fallback for any other parentheses if they start with metadata-like keys
  // but let's stick to the most common ones to avoid stripping actual story titles like "Hồi 1 (Thượng)"
  
  return { ...rest, title, storyGuidingPrinciple, pov };
};
