export const VIETNAMESE_FONTS = [
  { name: 'Inter', family: '"Inter", sans-serif' },
  { name: 'Roboto', family: '"Roboto", sans-serif' },
  { name: 'Open Sans', family: '"Open Sans", sans-serif' },
  { name: 'Montserrat', family: '"Montserrat", sans-serif' },
  { name: 'Playfair Display', family: '"Playfair Display", serif' },
  { name: 'Lora', family: '"Lora", serif' },
  { name: 'Merriweather', family: '"Merriweather", serif' },
  { name: 'Noto Sans', family: '"Noto Sans", sans-serif' },
  { name: 'Noto Serif', family: '"Noto Serif", serif' },
  { name: 'Source Sans Pro', family: '"Source Sans Pro", sans-serif' },
  { name: 'Source Serif Pro', family: '"Source Serif Pro", serif' },
  { name: 'Nunito', family: '"Nunito", sans-serif' },
  { name: 'Quicksand', family: '"Quicksand", sans-serif' },
  { name: 'Raleway', family: '"Raleway", sans-serif' },
  { name: 'Oswald', family: '"Oswald", sans-serif' },
  { name: 'Bitter', family: '"Bitter", serif' },
  { name: 'EB Garamond', family: '"EB Garamond", serif' },
  { name: 'Cormorant Garamond', family: '"Cormorant Garamond", serif' },
  { name: 'Mulish', family: '"Mulish", sans-serif' },
  { name: 'Be Vietnam Pro', family: '"Be Vietnam Pro", sans-serif' },
  { name: 'JetBrains Mono', family: '"JetBrains Mono", monospace' },
  { name: 'Fira Code', family: '"Fira Code", monospace' },
  { name: 'Space Mono', family: '"Space Mono", monospace' },
  { name: 'Inconsolata', family: '"Inconsolata", monospace' },
  { name: 'Source Code Pro', family: '"Source Code Pro", monospace' },
  { name: 'IBM Plex Mono', family: '"IBM Plex Mono", monospace' },
  { name: 'Ubuntu Mono', family: '"Ubuntu Mono", monospace' },
  { name: 'Courier Prime', family: '"Courier Prime", monospace' },
  { name: 'Share Tech Mono', family: '"Share Tech Mono", monospace' },
  { name: 'Chakra Petch', family: '"Chakra Petch", sans-serif' },
  { name: 'Bai Jamjuree', family: '"Bai Jamjuree", sans-serif' },
  { name: 'Saira', family: '"Saira", sans-serif' },
  { name: 'Exo 2', family: '"Exo 2", sans-serif' },
  { name: 'Space Grotesk', family: '"Space Grotesk", sans-serif' },
  { name: 'Outfit', family: '"Outfit", sans-serif' },
  { name: 'Lexend', family: '"Lexend", sans-serif' },
  { name: 'Kanit', family: '"Kanit", sans-serif' },
  { name: 'Mitr', family: '"Mitr", sans-serif' },
  { name: 'Sarabun', family: '"Sarabun", sans-serif' },
  { name: 'Comfortaa', family: '"Comfortaa", sans-serif' },
];

export const FONT_SIZES = [12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 36, 40, 48];
