export const CHARACTER_RULES = `
--- CẨM NANG XÂY DỰNG VÀ KHAI THÁC NHÂN VẬT (CHARACTER DEVELOPMENT GUIDELINES) ---
⚠️ **NGUYÊN TẮC TỐI THƯỢNG: BẢNG THÔNG TIN NHÂN VẬT LÀ PHÁP QUY**
- Mọi sáng tạo và cập nhật PHẢI dựa trên nền tảng của bảng thông tin nhân vật hiện có trong Story Bible.
- Tuyệt đối không được bỏ qua, mâu thuẫn hoặc tự ý thay đổi các thông tin đã thiết lập (Ngày sinh, Tuổi, Tính cách, Kim chỉ nam) của nhân vật cũ.
- Bảng thông tin nhân vật là "Nguồn sự thật duy nhất" (Single Source of Truth). Mọi biến đổi của nhân vật phải là quá trình tích lũy từ nội dung truyện và phải có giải trình (reason) thuyết phục.

1. CÁCH XUẤT HIỆN (CHARACTER INTRODUCTION)
- Quy tắc "Hành động định hình tính cách": Không bao giờ liệt kê khô khan (ví dụ: "A là người dũng cảm và lạnh lùng"). Hãy để họ xuất hiện đang làm một việc thể hiện rõ bản chất đó (ví dụ: A đang bình thản lau vết máu trên kiếm trong khi kẻ thù la hét).
- Ấn tượng đầu tiên (The Character Hook): Khoảnh khắc đầu tiên độc giả thấy nhân vật phải đáng nhớ và gợi sự tò mò.
- Gắn kết với bối cảnh: Nhân vật không xuất hiện trong không gian trống. Cách họ tương tác với môi trường xung quanh (đá văng một hòn sỏi, nhíu mày vì mùi ẩm mốc) tiết lộ vị thế và tâm trạng của họ.

2. CHIỀU SÂU VÀ BỐI CẢNH (DEPTH & BACKGROUND)
- Nguyên lý Tảng băng trôi: Những gì thể hiện ra ngoài (lời nói, hành động) chỉ là 20%. 80% còn lại là quá khứ, tổn thương, bí mật và khao khát thầm kín bị che giấu. Hãy hé lộ 80% này một cách từ từ qua các chi tiết nhỏ, không kể lể toàn bộ (info-dump).
- Điểm khiếm khuyết (Flaws): Nhân vật hoàn hảo là nhân vật chết. Họ phải có điểm yếu (kiêu ngạo, đa nghi, quá mềm lòng, ám ảnh quá khứ, bốc đồng, dễ bị dục vọng chi phối, thiếu thấu cảm...). Điểm yếu này phải gây ra rắc rối thực sự cho họ trong cốt truyện.
- Mâu thuẫn nội tâm (Internal Conflict): Sự giằng xé giữa "Điều họ muốn" (Want - ví dụ: trả thù, dục vọng cấm kỵ) và "Điều họ thực sự cần" (Need - ví dụ: sự bình yên, tha thứ, giữ vững đạo lý). Khai thác sự mâu thuẫn giữa trách nhiệm/đạo đức và bản năng/dục vọng.
- **Sự Đa Cực Của Diện Mạo & Nội Tâm (Persona Duality):** Xây dựng nhân vật sở hữu một diện mạo hoàn hảo (ví dụ: ngây thơ như trẻ con, rạng rỡ như ánh mặt trời) nhưng sâu bên trong lại là một "thú săn mồi" đầy toan tính. Sự đối lập giữa những lời làm nũng đáng yêu và suy nghĩa "muốn ăn sạch đối phương" chính là chìa khóa tạo nên sức hút kỳ lạ và sự kịch tính cho nhân vật.
- Quyền lực & Sự tha hóa (The Corruption of Power): Khai thác tâm lý của những kẻ nắm quyền lực tuyệt đối. Sự nhàm chán sinh ra từ việc "cái gì cũng có được" sẽ dẫn đến những khao khát lệch lạc, phá vỡ cấm kỵ để tìm kiếm cảm giác hồi hộp. Quyền lực không chỉ là sức mạnh, nó là chất xúc tác làm tha hóa nhân tính, dẫn đến việc lạm dụng quyền lực để ép buộc và thỏa mãn nhục dục.
- Khẩu chiến Quyền lực (Power-Play Dialogue): Những nhân vật có địa vị không chỉ giao tranh bằng vũ lực. Lời thoại của họ phải là một chiến trường của hệ tư tưởng, sự mỉa mai và áp đặt quyền lực. Kẻ mạnh dùng lời nói để tước đoạt hy vọng và logic của kẻ yếu trước khi ra tay.
- Sự hy sinh bi tráng (The Tragic Bargain): Nhân vật có thể chấp nhận đánh đổi nhân phẩm, tự tôn hoặc chịu đựng sự nhục nhã tột cùng (như chấp nhận làm nô lệ tình dục cho ân nhân/kẻ thù) không phải vì bản thân, mà để bảo vệ sự an nguy, cứu công ty hoặc tương lai của gia đình. Đây là đỉnh cao của sự giằng xé nội tâm: họ vừa hận kẻ chiếm đoạt, vừa tự nguyền rủa bản thân nhưng vẫn phải gồng mình phục vụ. Sự hiện diện của con tin là người thân (con gái/mẹ) khiến mọi sự phản kháng bốc hơi, thay vào đó là sự phối hợp đầy uất nghẹn và nước mắt.
- Đòn Bẩy Tâm Lý & Sự Cưỡng Ép Đa Tầng (Psychological Leverage): Khai thác sự ác độc khi dùng sự an nguy của người thân làm "con tin cảm xúc" (ví dụ: dùng tính mạng con gái ép mẹ quy phục). Ép buộc nạn nhân phải tự mình cởi đồ, trói tay hoặc dâm đãng phối hợp để đổi lấy mạng sống cho người thân ngay tại hiện trường. Sự giằng xé giữa bản năng bảo vệ và nỗi nhục nhã thể xác là chất liệu trung tâm.
- Sức mạnh của chi tiết vi mô (Obsessive Micro-interactions): Khắc họa sự si mê thông qua những chi tiết nhỏ nhặt nhưng có tác động tâm lý cực lớn. Một câu nói vô tình của đối tượng thầm mến có thể khiến nhân vật "vui vẻ cả ngày", hay một cái chạm tay nhẹ có thể khiến "nhục huyệt ngứa ngáy" hoặc "cơ thể run lên vì kích động". Mọi mô tả phải đi xuyên qua lăng kính của sự ám ảnh thầm kín.
- Sự đứt gãy giữa Liêm sỉ và Bản năng (The Dignity-Instinct Fracture): Miêu tả khoảnh khắc lý trí gào thét van xin "đừng làm thế" hoặc "đau quá" nhưng cơ thể lại vô thức phối hợp, hẩy mông đón nhận hoặc há miệng phục vụ do tác động của kích thích cực độ. Thể hiện sự bất lực khi "tiếng rên hừ hừ cứ thoát ra từ miệng" dù trong lòng đang thấy xấu hổ nóng ran cả người.
- Ám ảnh Cấm kỵ & Phản ứng Vô thức: Khai thác sâu sắc tâm lý trong các mối quan hệ cấm kỵ. Nhấn mạnh phản ứng cơ thể như "tay quờ quạng quào cấu tứ tung", "bấu chặt tay xuống giường rướm máu" khi bị bạo dâm phũ phàng. Sự tương phản giữa nỗi đau thể xác (như bị tét ra) và sự khoái lạc tột đỉnh làm biến dạng nhận thức nhân vật.
- Sự suy sụp Tâm lý (Psychological Degradation): Khi nhân vật trải qua các biến cố lớn (như bị cưỡng ép, phản bội, mất mát), phải miêu tả chi tiết sự suy sụp tinh thần, sự tê liệt cảm xúc, nỗi kinh hoàng, và những tổn thương tâm lý sâu sắc để lại di chứng lâu dài.

3. CÁC BƯỚC PHÁT TRIỂN (CHARACTER ARC)
- Tính chủ động & Thụ động (Agency vs. Passivity): Đây là các nét tính cách đặc trưng của nhân vật. Tuy nhiên, dù là nhân vật có tính cách thụ động, họ vẫn phải có "Agency" (Tính chủ động kể chuyện) – nghĩa là những quyết định, sự lựa chọn hoặc phản ứng của họ (ngay cả khi chọn không hành động) phải tạo ra hệ quả logic và góp phần thúc đẩy cốt truyện phát triển. Tuyệt đối không để nhân vật trôi dạt vô định mà không có bất kỳ tác động nào đến đại cục.
- Biến cố ép buộc (The Catalyst): Phải có sự kiện phá vỡ vùng an toàn, buộc nhân vật phải thay đổi hoặc bộc lộ bản chất thật.
- Trả giá để trưởng thành: Sức mạnh, nhận thức hay tình cảm không tự nhiên mà có. Nhân vật phải đổ máu, rơi nước mắt, hoặc đánh đổi thứ quan trọng để đạt được sự phát triển (Growth).

4. VAI TRÒ VÀ ĐÓNG GÓP CHO CỐT TRUYỆN (PLOT CONTRIBUTION)
- Không có nhân vật thừa: Mọi nhân vật (dù là phụ) đều phải phục vụ một mục đích: thúc đẩy cốt truyện, làm nổi bật chủ đề, hoặc làm chất xúc tác cho sự thay đổi của nhân vật chính. Nếu bỏ nhân vật đó đi mà truyện không ảnh hưởng, hãy xóa họ.
- Thế giới không xoay quanh Nhân vật chính (Anti-MC-Centrism): Nhân vật phụ không phải là công cụ phục vụ nhân vật chính. Họ là những thực thể sống có cuộc đời riêng đang diễn ra song song. Khi không xuất hiện trong cảnh quay, họ vẫn đang bận rộn với công việc, gia đình hoặc âm mưu của riêng mình. Tuyệt đối không để nhân vật phụ luôn túc trực hoặc chỉ tồn tại để giải quyết vấn đề cho nhân vật chính.
- Mạng lưới quan hệ (Web of Relationships): Khai thác sự tương tác chéo. Nhân vật A ảnh hưởng đến B thế nào? Sự xuất hiện của C làm thay đổi động lực giữa A và B ra sao?
- Phản diện có chiều sâu: Phản diện không ác chỉ vì thích ác. Họ phải có lý tưởng riêng, có logic riêng và tin rằng mình đang làm đúng. Sự đối đầu giữa Chính và Tà phải là sự va chạm về hệ tư tưởng, không chỉ là đánh nhau vật lý.
- QUY TẮC CHỐNG "HẮC HÓA" (ANTI-DARKNESS RULE): NGHIÊM CẤM tạo nhân vật chủ chốt có tính cách tham vọng, thủ đoạn, xấu xa, tồi tệ trừ khi có yêu cầu cụ thể. Với mọi thiết lập cấu hình và mọi thể loại, AI luôn bị cấm hắc hóa các nhân vật (biến họ thành kẻ xấu, nham hiểm, mưu mô) nếu người dùng không gợi ý hay yêu cầu hắc hóa. Mọi sự thay đổi về bản chất nhân vật phải có lý do cực kỳ thuyết phục và là kết quả của một quá trình biến cố lớn.
- Phân bổ đất diễn (Đặc biệt cho Harem/Nhiều nhân vật nữ): Khi có nhiều nhân vật, BẮT BUỘC phải chia cốt truyện và đất diễn một cách hợp lý tùy theo tình tiết. Tránh việc tập trung quá mức vào duy nhất một nhân vật mà bỏ rơi các nhân vật khác. Mỗi người đều phải có khoảnh khắc tỏa sáng và vai trò riêng biệt trong đại cục.

5. TÍNH CÁCH VÀ PHẢN ỨNG TRONG CẢNH THÂN MẬT (NSFW CHARACTERISTICS)
- Trinh tiết & Kinh nghiệm: Phản ánh trạng thái trinh tiết, mức độ kinh nghiệm tình dục và **quan điểm/suy nghĩ của nhân vật về tình dục** (ví dụ: coi trọng sự thuần khiết, xem đó là nhu cầu sinh lý bình thường, hay là sự gắn kết tâm hồn thiêng liêng...). Đây là thông tin quan trọng để điều chỉnh hành vi.
- Sự chuyển biến Tâm lý - Từ Tò mò đến Bản năng (Psychological Awakening): Khi viết về "lần đầu tiên" hoặc sự thức tỉnh giới tính, cần tập trung miêu tả sự bỡ ngỡ, sự khác biệt giữa tưởng tượng và thực tế. Nhấn mạnh sự tò mò, rụt rè ban đầu trước khi bị bản năng nguyên thủy lấn át. Khai thác sự "nhầm lẫn khoái cảm" khi mơ màng tỉnh giấc (Somnophilia) dẫn đến sự quy thuận mù quáng của cơ thể trước những kích thích bạo liệt và kích thước quá khổ, dù tâm trí còn đang lầm tưởng về danh tính đối phương.
- Logic Quy Thuận & Sự Phản Bội Của Giác Quan (Pleasure-Driven Submission): Trong các cảnh bạo lực hoặc cưỡng ép, nhân vật có thể bị "đánh gục" hoàn toàn bởi khoái cảm quá tải. Sự nóng bừng của dịch thể, cảm giác bị nong rộng hết mức và sự thâm nhập lút cán (từng chút một) tạo ra một cú sốc điện lên hệ thần kinh, khiến nhân vật dù muốn phản kháng nhưng cơ thể lại tự động phối hợp (ưỡn mông đón nhận, quấn chân giữ chặt) và quy thuận nguồn khoái lạc đó. Khai thác sự sa ngã của những phụ nữ vốn chuẩn mực (như Hương trong bối cảnh cán sự kiểm toán) nhanh chóng trở nên "hư hỏng" và "dâm dật" trước bản năng sinh tồn và thụ hưởng.
- Bình thường hóa & Nhất quán: Tuyệt đối không được bẻ cong tính cách nhân vật sau khi làm tình. Tình dục là một phần của cuộc sống, không phải là thứ biến một người thanh cao thành dâm đãng hay một người mạnh mẽ thành yếu đuối một cách phi logic. Nhân vật sau khi ân ái vẫn phải giữ được bản sắc, phong thái và trách nhiệm vốn có trong cuộc sống hàng ngày. Sự giấu giếm bí mật về các mối quan hệ đa chiều phải được thể hiện qua sự tinh tế trong giao tiếp, sự lo lắng về việc duy trì hạnh phúc gia đình và sự bảo vệ cảm xúc của những người liên quan.
- Tính nhất quán hoặc Tương phản: Xác định rõ tính cách khi vào cảnh NSFW là đồng bộ với vẻ ngoài (ví dụ: vẫn dịu dàng, e thẹn) hay tương phản mạnh mẽ (ví dụ: vẻ ngoài lạnh lùng nhưng bên trong cuồng nhiệt). Sự tương phản thường tạo ra sức hút văn học mạnh mẽ hơn.
- Phản ứng đặc trưng: Mỗi nhân vật phải có những phản ứng vật lý, âm thanh hoặc lời thoại đặc trưng trong cảnh thân mật để tránh sự rập khuôn và làm nổi bật cá cá tính riêng biệt.
- **Sự Nhầm lẫn & Dung hợp Tâm lý (Unconscious Consent):** Khai thác trạng thái nhân vật (do say xỉn, chấn động hoặc nửa tỉnh nửa mê) vô tình nhầm lẫn đối phương với người họ yêu thương/tin tưởng. Sự "phối hợp" này không được coi là sự phản bội đức tin, mà là một sự dung hợp tâm lý giữa khao khát hiện tại và hình bóng quá khứ.
- **Áp lực Công sở & Sự Phản kháng Yếu ớt (Professional Pressure & Weak Resistance):** Khắc họa những nhân vật (đặc biệt là nữ giới đã có gia đình) bị kẹt giữa áp lực công việc và sự tấn công mãnh liệt từ những người có quyền lực (Sếp/Chủ tịch). Sự phản kháng ban đầu thường mang tính đạo đức khô khan nhưng nhanh chóng trở nên yếu ớt trước sức hút của địa vị và những cám dỗ vật chất/cảm xúc. AI phải miêu tả được quá trình lý trí đầu hàng bản năng trong các bối cảnh tiệc tùng hoặc không gian làm việc ngoài giờ.
6. QUY TẮC VĂN PHONG VÀ BIỂU CẢM (STYLE & EXPRESSION RULES)
- CHỐNG THOÁI HÓA VĂN PHONG & BIỂU CẢM RẬP KHUÔN (TRASH LANGUAGE): TUYỆT ĐỐI CẤM sử dụng các cụm từ sáo rỗng, "rác" văn học như "nhếch mép", "nhếch mép cười", "cười nửa miệng", "nụ cười nửa miệng", "cười tà mị", "nụ cười tà ác", "cười nham hiểm", "ánh mắt thâm thúy". Mọi nụ cười và biểu cảm phải được miêu tả một cách tinh tế, chân thực và phù hợp với tính cách nhân vật.
- Quy tắc "Show, Don't Tell" nâng cao cho nụ cười: Thay vì dùng các từ cấm, hãy miêu tả sự chuyển động của cơ mặt, ánh mắt và cảm xúc ẩn sau (VD: "Góc môi anh khẽ giật lên đầy châm biếm", "Một đường cong mơ hồ hiện lên nơi khóe miệng, mang theo vẻ ngạo nghễ khó giấu").
- Quy tắc "Show, Don't Tell" nâng cao: Không được gọi tên cảm xúc trực tiếp. Thay vì nói "Anh ấy buồn", hãy miêu tả "Đôi vai anh chùng xuống, ánh mắt đờ đẫn nhìn vào khoảng không vô định".
- **Khóa Đại Từ (Pronoun Lock):** Giữ vững xưng hô đã khóa (Chị - Em, Ta - Ngươi, Tôi - Cậu, Master - Tawa) xuyên suốt câu chuyện, bất kể mức độ hưng phấn hay bối cảnh thay đổi, trừ khi có sự thay đổi vị thế cực lớn được Master phê duyệt.
- **Quy tắc xưng hô lịch sự (QUAN TRỌNG):** 
    + Hạn chế tối đa việc sử dụng các đại từ mang tính suồng sã hoặc coi thường như "Mày", "Tao", "Hắn", "Ngươi" trừ khi bối cảnh cực kỳ thù địch hoặc nhân vật phản diện đang mắng chửi.
    + Đặc biệt đối với **Nhân vật chính cốt lõi**, AI phải sử dụng cách xưng hô tôn trọng, phù hợp với vị thế và tính cách (Ví dụ: Anh, Cô, Chàng trai, Nàng, hoặc tên riêng).
    + Tuyệt đối không sử dụng các câu mắng chửi, xúc phạm nhân phẩm nhân vật chính trừ khi đó là lời thoại của kẻ thù trong một tình huống xung đột cụ thể.

7. QUY TẮC ĐẶT TÊN (NAMING RULES)
- **Họ tên đầy đủ & Danh xưng:** Bắt buộc phải có đầy đủ Họ và Tên. Luôn đi kèm danh xưng/chức danh phù hợp (Thầy, Cô, Giám đốc, Trưởng lão...).
- **Nhất quán với Thể loại & Ưu tiên:** 
    + **QUY TẮC MẶC ĐỊNH TỐI THƯỢNG:** Nếu không có yêu cầu cụ thể về quốc gia hay bối cảnh, hãy LUÔN ƯU TIÊN sử dụng tên gọi và bối cảnh Trung Quốc (Hán Việt) thay vì Việt Nam. 
    + **NGOẠI LỆ LINH HOẠT:** Mặc dù ưu tiên Trung Quốc, nhưng nếu Thể loại đã đặc thù hoặc có yêu cầu thiết lập rõ bối cảnh một quốc gia khác (Isekai/Light Novel của Nhật Bản, Western Fantasy Phương Tây, Đô thị Mỹ/Hàn Quốc...), AI BẮT BUỘC sử dụng đúng hệ thống bối cảnh và tên gọi thuộc quốc gia/thể loại đó, tuyệt đối không áp đặt ngôn ngữ Hán Việt sai bối cảnh.
    + Tiên hiệp/Võ hiệp: Dùng 100% Hán Việt hoa mỹ.
    + Đô thị mặc định: Ưu tiên dùng tên Trung Quốc và bối cảnh Trung Quốc (Hán Việt). Tuyệt đối không dùng tên Việt Nam trừ khi có yêu cầu cường điệu.
    + Fantasy/Bối cảnh Tây: Dùng tên kiểu Tây/Latin.
    + Light Novel/Isekai/Manhwa: Dùng tên gốc Nhật/Hàn (không phiên âm Hán Việt).
- **Tính biểu tượng:** Tên nên gợi ý về tính cách hoặc số phận nhân vật (ví dụ: tên thanh cao cho người chính trực, tên trầm mặc cho người u buồn).
`;
